export const DUMMY_POIS = [
  {
    id: 'dummy-tacos-guero',
    nombre: 'Tacos El Guero',
    descripcion: 'Legendarios tacos al pastor en el corazón del Centro Histórico. Una parada obligatoria para cualquier entusiasta de la gastronomía mexicana.',
    categoria: 'comida',
    latitud: 19.4323,
    longitud: -99.1332,
    direccion: 'Calle República de Uruguay 27, Centro Histórico, CDMX',
    emoji: '🌮',
    foto_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865ef4?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$',
    horario_apertura: '09:00',
    horario_cierre: '23:00',
    especialidades: ['Tacos al Pastor', 'Costra de Queso', 'Agua de Horchata'],
    telefono: '55 1234 5678',
    instagram: 'tacoselguero_mx',
    facebook: 'TacosElGueroOficial',
    productos: [
      { id: 'p1', nombre: 'Orden de 5 Tacos al Pastor', precio: 85, descripcion: 'Con piña, cebolla y cilantro.' },
      { id: 'p2', nombre: 'Gringa de Sirloin', precio: 65, descripcion: 'Queso fundido y carne premium.' }
    ]
  },
  {
    id: 'dummy-coppel-reforma',
    nombre: 'Coppel Reforma',
    descripcion: 'Tu tienda departamental favorita en la avenida más emblemática de México. Lo mejor en moda, tecnología y hogar con la confianza de siempre.',
    categoria: 'tienda',
    latitud: 19.4298,
    longitud: -99.1558,
    direccion: 'Paseo de la Reforma 250, Juárez, CDMX',
    emoji: '🛍️',
    foto_url: 'https://images.unsplash.com/photo-1573855619003-97b4799dcd8b?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '10:00',
    horario_cierre: '20:00',
    especialidades: ['Moda Deportiva', 'Electrónica', 'Hogar Digital'],
    telefono: '800 220 7735',
    instagram: 'coppel',
    facebook: 'tiendascoppel',
    productos: [
      { id: 'p1', nombre: 'Smart TV 4K 55"', precio: 8999, descripcion: 'Lo último en tecnología visual.' },
      { id: 'p2', nombre: 'Tenis de Running', precio: 1299, descripcion: 'Comodidad para tus recorridos por la ciudad.' },
      { id: 'p3', nombre: 'iPhone 15 Promax', precio: 28999, descripcion: 'Apple original con Coppel Pay.' }
    ]
  },
  {
    id: 'dummy-museo-soumaya',
    nombre: 'Museo Soumaya',
    descripcion: 'Icono arquitectónico que alberga una de las colecciones de arte más importantes del mundo.',
    categoria: 'cultural',
    latitud: 19.4407,
    longitud: -99.2047,
    direccion: 'Boulervard Miguel de Cervantes Saavedra 303, CDMX',
    emoji: '🏛️',
    foto_url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: 'Gratis',
    horario_apertura: '10:30',
    horario_cierre: '18:30',
    especialidades: ['Esculturas de Rodin', 'Impresionismo'],
    productos: []
  },
  {
    id: 'dummy-coffee-bean',
    nombre: 'The Coffee Bean',
    descripcion: 'El refugio perfecto en Polanco para los amantes del café de especialidad. Granos seleccionados y repostería artesanal en un ambiente relajado.',
    categoria: 'comida',
    latitud: 19.4300,
    longitud: -99.1901,
    direccion: 'Emilio Castelar 135, Polanco, CDMX',
    emoji: '☕',
    foto_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '07:00',
    horario_cierre: '22:00',
    especialidades: ['Cold Brew Nitrogenado', 'Café Geisha'],
    productos: [
      { id: 'p1', nombre: 'Flat White Doble', precio: 75, descripcion: 'Equilibrio perfecto entre espresso y leche.' },
      { id: 'p2', nombre: 'Croissant Mantequilla', precio: 55, descripcion: 'Recién horneado.' }
    ]
  },
  {
    id: 'dummy-angel-independencia',
    nombre: 'Ángel de la Independencia',
    descripcion: 'Monumento emblemático de la Ciudad de México y punto de encuentro para celebraciones nacionales.',
    categoria: 'cultural',
    latitud: 19.4270,
    longitud: -99.1677,
    direccion: 'Paseo de la Reforma y Eje 2 PTE, CDMX',
    emoji: '🗽',
    foto_url: 'https://images.unsplash.com/photo-1518182170546-07661fd94144?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: 'Gratis',
    horario_apertura: '00:00',
    horario_cierre: '23:59',
    especialidades: ['Mirador', 'Fotografía', 'Historia'],
    productos: []
  },
  {
    id: 'dummy-gym-power',
    nombre: 'Power Fit Gym',
    descripcion: '',
    categoria: 'servicios',
    latitud: 19.4124,
    longitud: -99.1652,
    direccion: 'Av. Insurgentes Sur 452, CDMX',
    emoji: '🏋️‍♂️',
    foto_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop',
    verificado: false,
    activo: true,
    precio_rango: '$$$',
    horario_apertura: '05:00',
    horario_cierre: '23:00',
    especialidades: ['Crossfit', 'Pesas', 'Cardio'],
    productos: [
      { id: 'g1', nombre: 'Membresía Mensual', precio: 800, descripcion: 'Acceso total a instalaciones.' },
      { id: 'g2', nombre: 'Pase de Visita', precio: 150, descripcion: 'Acceso por un solo día.' }
    ]
  },
  {
    id: 'dummy-cine-magico',
    nombre: 'Cine Mágico VIP',
    descripcion: 'Disfruta de los últimos estrenos en salas hiper premium con butacas reclinables, sushi y mixología.',
    categoria: 'servicios',
    latitud: 19.4444,
    longitud: -99.1555,
    direccion: 'Plaza Central 4to Piso, CDMX',
    emoji: '🍿',
    foto_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$$$',
    horario_apertura: '13:00',
    horario_cierre: '23:30',
    especialidades: ['Películas 4D', 'Sushi', 'Coctelería'],
    productos: [
      { id: 'cin1', nombre: 'Boleto Sala VIP', precio: 220, descripcion: 'Asiento sofá cama.' },
      { id: 'cin2', nombre: 'Combo Pareja Mágica', precio: 350, descripcion: '2 Refrescos Jumbos, Palomitas mitad caramelo y 1 Hotdog.' }
    ]
  },
  {
    id: 'dummy-barberia',
    nombre: 'The Classic Barber',
    descripcion: 'Cortes de cabello tradicionales con navaja y ritual de toalla caliente.',
    categoria: 'servicios',
    latitud: 19.4201,
    longitud: -99.1671,
    direccion: 'Roma Norte, CDMX',
    emoji: '💈',
    foto_url: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=80&w=1000&auto=format&fit=crop',
    verificado: false,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '10:00',
    horario_cierre: '20:00',
    especialidades: ['Desvanecidos', 'Barba', 'Faciales'],
    productos: [
      { id: 'b1', nombre: 'Corte + Barba', precio: 400, descripcion: 'Alineación perfecta.' }
    ]
  },
  {
    id: 'dummy-sushi-roll',
    nombre: 'Samurai Sushi',
    descripcion: '',
    categoria: 'comida',
    latitud: 19.4310,
    longitud: -99.1415,
    direccion: 'Alameda Central, Local 4, CDMX',
    emoji: '🍣',
    foto_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '13:00',
    horario_cierre: '22:00',
    especialidades: ['Rollos Empanizados', 'Ramen', 'Sake'],
    productos: [
      { id: 'su1', nombre: 'Samurai Dragon Roll', precio: 180, descripcion: 'Aguacate, camarón empanizado y salsa anguila.' },
      { id: 'su2', nombre: 'Ramen Tradicional Shoyu', precio: 220, descripcion: 'Fideos artesanales.' }
    ]
  },
  {
    id: 'dummy-libreria',
    nombre: 'Librería El Péndulo',
    descripcion: 'Un paraíso para intelectuales. Libros, café, música y una arquitectura espectacular.',
    categoria: 'tienda',
    latitud: 19.4180,
    longitud: -99.1600,
    direccion: 'Álvaro Obregón 86, Roma Norte, CDMX',
    emoji: '📚',
    foto_url: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '09:00',
    horario_cierre: '21:00',
    especialidades: ['Desayunos', 'Libros de Arte', 'Vinilos'],
    productos: []
  },
  {
    id: 'dummy-hotel-boutique',
    nombre: 'Casa Elegancia Hotel',
    descripcion: 'Hospedaje premium en el corazón bohemio. Alberca en el techo y 5 estrellas reales.',
    categoria: 'servicios',
    latitud: 19.4130,
    longitud: -99.1710,
    direccion: 'Condesa, CDMX',
    emoji: '🏨',
    foto_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$$$',
    horario_apertura: '00:00',
    horario_cierre: '23:59',
    especialidades: ['Spa', 'Room Service 24/7', 'Rooftop Bar'],
    productos: [
      { id: 'ho1', nombre: 'Noche Suite Presidencial', precio: 4500, descripcion: 'Vista al parque, tina hidromasaje.' },
      { id: 'ho2', nombre: 'Masaje de Tejido Profundo', precio: 1200, descripcion: '60 minutos de pura relajación en el Spa.' }
    ]
  },
  {
    id: 'dummy-heladeria',
    nombre: 'Gelato Ciao',
    descripcion: 'Helado italiano auténtico batido frente a ti.',
    categoria: 'comida',
    latitud: 19.4350,
    longitud: -99.1450,
    direccion: 'Av Juarez, CDMX',
    emoji: '🍦',
    foto_url: 'https://images.unsplash.com/photo-1570197781417-0a52375c3171?q=80&w=1000&auto=format&fit=crop',
    verificado: false,
    activo: true,
    precio_rango: '$',
    horario_apertura: '11:00',
    horario_cierre: '20:00',
    especialidades: ['Pistacho DOP', 'Stracciatella'],
    productos: []
  },
  {
    id: 'dummy-coppel-centro',
    nombre: 'Coppel Centro Histórico',
    descripcion: 'Ropa, muebles, y tu banco BanCoppel en el centro de la ciudad.',
    categoria: 'tienda',
    latitud: 19.4310,
    longitud: -99.1360,
    direccion: 'República de Venustiano Carranza 57, CDMX',
    emoji: '🛍️',
    foto_url: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '09:00',
    horario_cierre: '20:30',
    especialidades: ['Muebles', 'Línea Blanca', 'Motos'],
    productos: [
      { id: 'cp1', nombre: 'Refrigerador Mabe', precio: 8599, descripcion: 'Ahorro de energía A+.' },
      { id: 'cp2', nombre: 'Motocicleta Vento 150', precio: 18999, descripcion: 'Llévatela a crédito Coppel.' }
    ]
  },
  {
    id: 'dummy-tienda-mascotas',
    nombre: 'Pet World Roma',
    descripcion: '',
    categoria: 'tienda',
    latitud: 19.4170,
    longitud: -99.1620,
    direccion: 'Orizaba 50, Roma Norte',
    emoji: '🐕',
    foto_url: 'https://images.unsplash.com/photo-1516734212822-43013e980596?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '10:00',
    horario_cierre: '19:00',
    especialidades: ['Alimento Premium', 'Estética Canina'],
    productos: [
      { id: 'pw1', nombre: 'Estética Completa', precio: 350, descripcion: 'Corte, baño, uñas, glándulas.' },
      { id: 'pw2', nombre: 'Croquetas Salmón Premium', precio: 1400, descripcion: 'Saco de 12 Kg.' }
    ]
  },
  {
    id: 'dummy-galeria-arte',
    nombre: 'Galería OMR',
    descripcion: 'Espacio dedicado al arte contemporáneo mexicano e internacional en un ambiente brutalista.',
    categoria: 'cultural',
    latitud: 19.4150,
    longitud: -99.1666,
    direccion: 'Córdoba 100, Roma Norte',
    emoji: '🖼️',
    foto_url: 'https://images.unsplash.com/photo-1549492193-4a11f67f2b98?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: 'Gratis',
    horario_apertura: '10:00',
    horario_cierre: '17:00',
    especialidades: ['Exposiciones Temporales', 'Arte Conceptual'],
    productos: []
  },
  // ─── ZONA SANTA FE ──────────────────────────────────────
  {
    id: 'dummy-centro-santafe',
    nombre: 'Centro Santa Fe',
    descripcion: 'El centro comercial más grande de América Latina. Más de 500 tiendas, cines, pista de hielo y la mejor oferta gastronómica de la zona poniente.',
    categoria: 'tienda',
    latitud: 19.3590,
    longitud: -99.2760,
    direccion: 'Av. Vasco de Quiroga 3800, Santa Fe, CDMX',
    emoji: '🏬',
    foto_url: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$$',
    horario_apertura: '11:00',
    horario_cierre: '21:00',
    especialidades: ['Moda Internacional', 'Pista de Hielo', 'Food Court Premium'],
    productos: [
      { id: 'csf1', nombre: 'Gift Card Centro Santa Fe', precio: 500, descripcion: 'Válida en todas las tiendas participantes.' }
    ]
  },
  {
    id: 'dummy-coppel-santafe',
    nombre: 'Coppel Santa Fe',
    descripcion: 'Tu sucursal Coppel favorita en la zona más moderna de la ciudad. BanCoppel, Afore Coppel y toda la línea de productos.',
    categoria: 'tienda',
    latitud: 19.3615,
    longitud: -99.2740,
    direccion: 'Av. Vasco de Quiroga 3850, Santa Fe, CDMX',
    emoji: '🛍️',
    foto_url: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '09:00',
    horario_cierre: '21:00',
    especialidades: ['BanCoppel', 'Electrónica', 'Muebles'],
    productos: [
      { id: 'csf_c1', nombre: 'Laptop Gamer ASUS', precio: 18999, descripcion: 'Procesador i7, 16GB RAM, RTX 4060.' },
      { id: 'csf_c2', nombre: 'Sala Moderna 3 piezas', precio: 12999, descripcion: 'Tela antimanchas, crédito Coppel disponible.' }
    ]
  },
  {
    id: 'dummy-ibero',
    nombre: 'Universidad Iberoamericana',
    descripcion: 'Una de las universidades privadas más prestigiosas de México. Campus con áreas verdes, galerías de arte y cafeterías estudiantiles.',
    categoria: 'cultural',
    latitud: 19.3700,
    longitud: -99.2635,
    direccion: 'Prolongación Paseo de la Reforma 880, Santa Fe',
    emoji: '🎓',
    foto_url: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: 'Gratis',
    horario_apertura: '07:00',
    horario_cierre: '22:00',
    especialidades: ['Galería Universitaria', 'Biblioteca', 'Cafetería Ibero'],
    productos: []
  },
  {
    id: 'dummy-sushi-santafe',
    nombre: 'Nobu Santa Fe',
    descripcion: 'Cocina japonesa de autor con influencia peruana en un ambiente exclusivo con vista a la ciudad.',
    categoria: 'comida',
    latitud: 19.3580,
    longitud: -99.2720,
    direccion: 'Centro Comercial Garden Santa Fe, Piso 3',
    emoji: '🍣',
    foto_url: 'https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$$$',
    horario_apertura: '13:00',
    horario_cierre: '23:00',
    especialidades: ['Omakase', 'Black Cod Miso', 'Cocteles Japoneses'],
    productos: [
      { id: 'nb1', nombre: 'Omakase 12 tiempos', precio: 2800, descripcion: 'Experiencia del chef con ingredientes de temporada.' },
      { id: 'nb2', nombre: 'Black Cod Miso', precio: 680, descripcion: 'El platillo insignia de Nobu.' }
    ]
  },
  {
    id: 'dummy-cafe-santafe',
    nombre: 'Café Punta del Cielo Santa Fe',
    descripcion: 'Café 100% mexicano de especialidad. Granos de Chiapas y Oaxaca tostados artesanalmente.',
    categoria: 'comida',
    latitud: 19.3620,
    longitud: -99.2690,
    direccion: 'Av. Santa Fe 440, Local 12',
    emoji: '☕',
    foto_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '07:00',
    horario_cierre: '21:00',
    especialidades: ['Cappuccino Chiapaneco', 'Pan Artesanal', 'Wifi Rápido'],
    productos: [
      { id: 'pdc1', nombre: 'Americano Grande', precio: 52, descripcion: 'Grano de altura de Chiapas.' },
      { id: 'pdc2', nombre: 'Frappé de Cajeta', precio: 78, descripcion: 'Con leche de almendra.' }
    ]
  },
  {
    id: 'dummy-gym-santafe',
    nombre: 'Smart Fit Santa Fe',
    descripcion: 'Gimnasio 24/7 con equipo de última generación y clases grupales incluidas.',
    categoria: 'servicios',
    latitud: 19.3640,
    longitud: -99.2710,
    direccion: 'Av. Javier Barros Sierra 540, Santa Fe',
    emoji: '💪',
    foto_url: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$',
    horario_apertura: '00:00',
    horario_cierre: '23:59',
    especialidades: ['24 Horas', 'Spinning', 'Peso Libre'],
    productos: [
      { id: 'sf1', nombre: 'Plan Mensual Smart', precio: 449, descripcion: 'Acceso a todas las sucursales.' },
      { id: 'sf2', nombre: 'Plan Black', precio: 649, descripcion: 'Incluye regaderas, toallas y app premium.' }
    ]
  },
  {
    id: 'dummy-garden-santafe',
    nombre: 'Garden Santa Fe',
    descripcion: 'Plaza con concepto jardín al aire libre. Restaurantes gourmet, boutiques y un ambiente único.',
    categoria: 'tienda',
    latitud: 19.3575,
    longitud: -99.2730,
    direccion: 'Guillermo González Camarena 1205, Santa Fe',
    emoji: '🌿',
    foto_url: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$$',
    horario_apertura: '10:00',
    horario_cierre: '22:00',
    especialidades: ['Terrazas', 'Boutiques', 'Gastro Bar'],
    productos: []
  },
  {
    id: 'dummy-tacos-santa',
    nombre: 'Los Sazones de Santa Fe',
    descripcion: 'Antojitos mexicanos tradicionales en plena zona corporativa. El favorito de los godínez de la zona.',
    categoria: 'comida',
    latitud: 19.3650,
    longitud: -99.2680,
    direccion: 'Av. Santa Fe 94, Col. Santa Fe',
    emoji: '🌮',
    foto_url: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?q=80&w=1000&auto=format&fit=crop',
    verificado: false,
    activo: true,
    precio_rango: '$',
    horario_apertura: '08:00',
    horario_cierre: '18:00',
    especialidades: ['Quesadillas', 'Tlacoyos', 'Aguas Frescas'],
    productos: [
      { id: 'lsz1', nombre: 'Combo Godín (3 quesadillas + agua)', precio: 75, descripcion: 'Queso, flor de calabaza y huitlacoche.' }
    ]
  },
  {
    id: 'dummy-cowork-santafe',
    nombre: 'WeWork Reforma Santa Fe',
    descripcion: 'Espacio de coworking premium con salas de juntas, café ilimitado y eventos de networking.',
    categoria: 'servicios',
    latitud: 19.3660,
    longitud: -99.2650,
    direccion: 'Prolongación Paseo de la Reforma 1015, Santa Fe',
    emoji: '💻',
    foto_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$$',
    horario_apertura: '06:00',
    horario_cierre: '23:00',
    especialidades: ['Hot Desk', 'Sala de Juntas', 'Café Ilimitado'],
    productos: [
      { id: 'ww1', nombre: 'Hot Desk Diario', precio: 450, descripcion: 'Acceso por un día con café y wifi.' },
      { id: 'ww2', nombre: 'Oficina Privada 4 personas', precio: 18000, descripcion: 'Mensual, todo incluido.' }
    ]
  },
  {
    id: 'dummy-parque-labatida',
    nombre: 'Parque La Mexicana',
    descripcion: 'El Central Park de Santa Fe. 30 hectáreas de áreas verdes, lago artificial, pista de correr y pet park.',
    categoria: 'cultural',
    latitud: 19.3630,
    longitud: -99.2780,
    direccion: 'Av. Javier Barros Sierra S/N, Santa Fe',
    emoji: '🌳',
    foto_url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: 'Gratis',
    horario_apertura: '05:00',
    horario_cierre: '22:00',
    especialidades: ['Lago Artificial', 'Dog Park', 'Foodtrucks'],
    productos: []
  },
  {
    id: 'dummy-farmacia-sf',
    nombre: 'Farmacia San Pablo Santa Fe',
    descripcion: '',
    categoria: 'servicios',
    latitud: 19.3605,
    longitud: -99.2700,
    direccion: 'Av. Vasco de Quiroga 3200, Santa Fe',
    emoji: '💊',
    foto_url: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '07:00',
    horario_cierre: '23:00',
    especialidades: ['Farmacia 24h', 'Dermocosmética', 'Servicio a Domicilio'],
    productos: []
  },
  {
    id: 'dummy-pizza-sf',
    nombre: 'Dominos Pizza Santa Fe',
    descripcion: 'Pizza en 30 minutos o menos. La favorita para juntas express y noches de gaming.',
    categoria: 'comida',
    latitud: 19.3610,
    longitud: -99.2660,
    direccion: 'Av. Santa Fe 380, Local 2',
    emoji: '🍕',
    foto_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '11:00',
    horario_cierre: '23:30',
    especialidades: ['Pizza Artesanal', 'Breadsticks', 'Delivery Rápido'],
    productos: [
      { id: 'dp1', nombre: 'Pepperoni Grande', precio: 199, descripcion: 'Masa original con doble queso.' },
      { id: 'dp2', nombre: 'Mega Dominos 2x1', precio: 349, descripcion: 'Dos pizzas grandes por el precio de una.' }
    ]
  },
  {
    id: 'dummy-oxxo-sf',
    nombre: 'OXXO Santa Fe',
    descripcion: '',
    categoria: 'tienda',
    latitud: 19.3635,
    longitud: -99.2695,
    direccion: 'Av. Santa Fe esquina Prolongación Reforma',
    emoji: '🏪',
    foto_url: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?q=80&w=1000&auto=format&fit=crop',
    verificado: false,
    activo: true,
    precio_rango: '$',
    horario_apertura: '00:00',
    horario_cierre: '23:59',
    especialidades: ['Recargas', 'Snacks', 'Pagos de Servicios'],
    productos: []
  },
  {
    id: 'dummy-starbucks-sf',
    nombre: 'Starbucks Reserve Santa Fe',
    descripcion: 'La experiencia premium de Starbucks con métodos de extracción artesanal, Siphon y Chemex.',
    categoria: 'comida',
    latitud: 19.3595,
    longitud: -99.2745,
    direccion: 'Centro Santa Fe, Planta Baja',
    emoji: '☕',
    foto_url: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$$',
    horario_apertura: '07:00',
    horario_cierre: '22:00',
    especialidades: ['Reserve Bar', 'Nitro Cold Brew', 'Repostería Artesanal'],
    productos: [
      { id: 'sbr1', nombre: 'Reserve Siphon Coffee', precio: 120, descripcion: 'Extracción al vacío con granos selectos.' },
      { id: 'sbr2', nombre: 'Frappuccino Reserve', precio: 95, descripcion: 'Edición limitada de temporada.' }
    ]
  },
  {
    id: 'dummy-cinepolis-sf',
    nombre: 'Cinépolis VIP Santa Fe',
    descripcion: 'Salas premium con servicio de mesero, menú gourmet y mixología mientras disfrutas el estreno.',
    categoria: 'servicios',
    latitud: 19.3585,
    longitud: -99.2755,
    direccion: 'Centro Santa Fe, 3er Piso',
    emoji: '🎬',
    foto_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$$',
    horario_apertura: '12:00',
    horario_cierre: '00:00',
    especialidades: ['IMAX', 'VIP Platino', 'Meseros en Sala'],
    productos: [
      { id: 'cin_sf1', nombre: 'Boleto VIP Platino', precio: 280, descripcion: 'Butaca reclinable con servicio.' },
      { id: 'cin_sf2', nombre: 'Combo Cinéfilo', precio: 220, descripcion: 'Palomitas gourmet + bebida craft.' }
    ]
  }
];
